apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      httpMethod: GET
      tracesDurationInMillis: false
      # If you later add Prometheus for service-graph generation, set:
      # serviceMap:
      #   datasourceUid: prometheus